.TH "C:/Users/Mani/source/repos/i4swt/swt-gruppe30-exercise2-calculator-extended/Calculator/obj Directory Reference" 3 "Wed Jan 30 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Mani/source/repos/i4swt/swt-gruppe30-exercise2-calculator-extended/Calculator/obj Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.in -1c
