.TH "C:/Users/Mani/source/repos/i4swt/swt-gruppe30-exercise2-calculator-extended/Calculator/Calculator.cs" 3 "Wed Jan 30 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Mani/source/repos/i4swt/swt-gruppe30-exercise2-calculator-extended/Calculator/Calculator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalculator\&.Calculator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCalculator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
