.TH "Calculator.CalculatorExtended" 3 "Wed Jan 30 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calculator.CalculatorExtended \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCalculator\&.Calculator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalculatorExtended\fP ()"
.br
.RI "Initializes a new instance of the \fBCalculatorExtended\fP class\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBAdd\fP (double firstValue, double secondValue)"
.br
.in -1c
.SH "Detailed Description"
.PP 



.SH "Constructor & Destructor Documentation"
.PP 
.SS "Calculator\&.CalculatorExtended\&.CalculatorExtended ()"

.PP
Initializes a new instance of the \fBCalculatorExtended\fP class\&. 
.SH "Member Function Documentation"
.PP 
.SS "static double Calculator\&.CalculatorExtended\&.Add (double firstValue, double secondValue)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
