.TH "Calculator.Calculator" 3 "Wed Jan 30 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calculator.Calculator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCalculator\&.CalculatorExtended\fP, and \fBCalculator\&.CopyOfCalculatorExtended\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBAdd\fP (double firstValue, double secondValue)"
.br
.RI "Adds the specified first value\&. "
.ti -1c
.RI "static double \fBSubstract\fP (double a, double b)"
.br
.RI "This info goes where? "
.ti -1c
.RI "static double \fBPower\fP (double x, double exp)"
.br
.ti -1c
.RI "static double \fBMultiply\fP (double a, double b)"
.br
.RI "Multiplies the specified a\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static double Calculator\&.Calculator\&.Add (double firstValue, double secondValue)\fC [static]\fP"

.PP
Adds the specified first value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfirstValue\fP The first value\&.
.br
\fIsecondValue\fP The second value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static double Calculator\&.Calculator\&.Multiply (double a, double b)\fC [static]\fP"

.PP
Multiplies the specified a\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP a\&.
.br
\fIb\fP The b\&.
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static double Calculator\&.Calculator\&.Power (double x, double exp)\fC [static]\fP"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIx\fP 
.br
\fIexp\fP 
.RE
.PP

.SS "static double Calculator\&.Calculator\&.Substract (double a, double b)\fC [static]\fP"

.PP
This info goes where? 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
