.TH "C:/Users/Mani/source/repos/i4swt/swt-gruppe30-exercise2-calculator-extended/Calculator/obj/Debug/TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs" 3 "Wed Jan 30 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Mani/source/repos/i4swt/swt-gruppe30-exercise2-calculator-extended/Calculator/obj/Debug/TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
